
# Site settings
title: tiwnwp
email: 
description: I can't wait until I can upgrade this shitty meatsack.
baseurl: "" # the subpath of your site, e.g. /blog/
production_url: "http://sybr.us/" 
github_username:  aeyk
facebook_username: xMETALxAVOCADOxLIFE
lastfm_user: Aeyk

# Build settings
markdown: kramdown
profile_picture_caption: I'm such a babe.

highlighter: pygments
# github: 
